### ISSUE TITLE
Implement 'axis = -1' in ak.cartesian and ak.firsts

### ISSUE THREAD

**Issue by Superharz** [scikit-hep/awkward#574] opened 2020-12-05 13:13 UTC
The docs for ```ak.cartesian``` say:
`axis (int) – The dimension at which this operation is applied. The outermost dimension is 0, followed by 1, etc., and negative values count backward from the innermost: -1 is the innermost dimension, -2 is the next level up, etc.`

However, passing  ```axis = -1``` results in 
```
ValueError: the 'axis' of cartesian must be non-negative
```

```
Ak Version:
0.4.5
```

**Comment by Superharz** [comment] 2020-12-05 17:07
Same happens with ```ak.firsts(array, axis = -1)```
```
NotImplementedError: ak.firsts with axis=-1
```

**Comment by jpivarski** [comment] 2020-12-05 17:16
The documentation says that `axis < 0` is allowed because it's copy-pasted documentation for the `axis` parameter generally. It's hard enough to keep docstrings in sync with so much duplication (why, Python, do docstrings have to be string literals?!?), also having them change as features get added would be too much. So `axis < 0` is a missing implementation for `ak.cartesian`, not a bug, despite the fact that it disagrees with the documentation. I want to avoid the situation in which we update the code but forget to update the documentation!

At the time when `ak.cartesian` was first written, it would have been difficult to implement `axis < 0`, but it isn't anymore. This is now low-hanging fruit for anyone who's interested or for me if I have a half-hour block to fill (most of that time would be writing the tests).

In `ak.cartesian`'s internal `getfunction1` or `getfunction2` (not sure which, or if it needs to be both), the `depth` should be used to convert the `axis` into a `posaxis` with

```python
posaxis = layout.axis_wrap_if_negative(posaxis)
```

similar to the definition in `ak.to_regular`. The `posaxis` starts being equal to `axis`, but as soon as it can be converted, it is converted. See

https://github.com/scikit-hep/awkward-1.0/blob/5996899a390099c9637aafc21961d7a041f1ddf7/src/libawkward/Content.cpp#L1749-L1771

for what `axis_wrap_if_negative` does—it was written after `ak.cartesian` and `ak.firsts`, so that's why they don't take advantage of it yet.

In order to make `posaxis` "sticky," I made it a one-element list in `ak.to_regular`. Maybe I could have used a Python `global` or `nonlocal` keyword, but I didn't want to do anything that is Python version-dependent: changing a list in place is "sticky" in a way that reassigning a variable in a nested function isn't (because variables have function scope in Python). That's why the actual line in `ak.to_regular` is

```python
posaxis[0] = layout.axis_wrap_if_negative(posaxis[0])
```

All of the above applies equally to `ak.firsts` and wherever else negative `axis` is promised but not yet implemented.

(Thanks for finding this inconsistency! It was left unimplemented to get the most important parts of the project done, and can easily be forgotten. Now we have to clean up and make it agree with the documentation.  `:)`  )

**Comment by Superharz** [comment] 2020-12-05 17:24
That's nice to hear. I can live without it for the moment since I know the depth of my lists. But it'd be definetly a nice thing to have.

**Comment by jpivarski** [comment] 2020-12-09 00:53
In PR #582, I did what I described above.

**Closed as completed** 2020-12-09 02:34 UTC
Labels: feature, good first issue

**Comment by Superharz** [comment] 2020-12-09 09:17
Awesome!
