### ISSUE TITLE
Key for reducers

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/awkward#498] opened 2020-10-23 20:08 UTC
It would be nice to have some sort of keyed reducer functionality, either through a new `ak.minby` etc. or maybe an optional `ak.min(..., key=None)` argument. Right now, as far as I can tell, the canonical workaround for `ak.min(array, key=condition, axis=1)` is `ak.firsts(array[ak.argmin(condition, axis=1, keepdims=True)])`, although I haven't worked through if that is general for all axes arguments.

**Comment by jpivarski** [comment] 2020-10-23 20:18
This is a duplicate of #203.

To avoid complicating the interface of `ak.min` and `ak.max` (which are supposed to follow NumPy's, anyway), I think a new name is better: `ak.minby` and `ak.maxby`. (Also avoids the complication that all reducers go through the same code path and none of the other reducers would have an equivalent of this `condition`.)

The good news is that I think #203 can be implemented entirely in Python. The `ak.singletons` and `ak.firsts` were created to do minby/maxby—the only problem is that it's cumbersome. I encountered this difficulty while writing

https://github.com/jpivarski-talks/2020-04-08-eic-jlab/blob/master/2020-04-08-eic-jlab-EVALUATED.ipynb

**Closed as completed** 2020-10-23 20:21 UTC
Labels: duplicate, feature
