### ISSUE TITLE
string comparison of string typed array throws a UFuncTypeError

### ISSUE THREAD

**Issue by drahnreb** [scikit-hep/awkward#501] opened 2020-10-29 18:07 UTC
Minimal working example (hopefully better than the last one):
``` python
one = ak.Array(["uno", "dos", "tres"])
one_l = one.layout
two = ak.Array(["un", "deux", "trois", "quatre"])
two_l = two.layout
three = ak.Array(["onay", "ootay", "eethray"])
three_l = three.layout
assert ak.to_list(one_l.mergemany([two_l, three_l])) == ["uno", "dos", "tres", "un", "deux", "trois", "quatre", "onay", "ootay", "eethray"]
merged = one_l.mergemany([two_l, three_l])
```
Expected behavior:
``` python
one == "uno"
>>> <Array [True, False, False] type='3 * ?bool'>
merged == "longerstringthantyped"
>>> <Array [False, False, False, ... False, False] type='10 * ?bool'>
```
Bug:
``` python
ak.Array(merged) == "uno"
>>> UFuncTypeError: ufunc 'equal' did not contain a loop with signature matching types (dtype('S3'), dtype('S3')) -> dtype('bool')
```

Unfortunately, I haven't caught up with the changes lately. My preliminary check suggests that, this behavior was introduced with [v.0.2.37](https://github.com/scikit-hep/awkward-1.0/compare/0.2.36...0.2.37#diff-5c46d0b61253440d84e39816781d3277efccea7fb0a7997657c58856c5b21260) (more specifically with .mergemany() ([PR#449](https://github.com/scikit-hep/awkward-1.0/pull/449)), and quick guess somewhere around [here](https://github.com/scikit-hep/awkward-1.0/blob/5a90e58fab4d48f46dbc2ff3e14275eccb688349/src/libawkward/array/NumpyArray.cpp#L1596)).
I experienced this bug, when higher level functions like `from_arrow` (that call mergemany internally now) produced the same bug.

**Comment by jpivarski** [comment] 2020-10-30 23:08
Generally, you should use high-level functions, like [ak.concatenate](https://awkward-array.readthedocs.io/en/latest/_auto/ak.concatenate.html) to concatenate:

```python
>>> merged = ak.concatenate([one, two, three])
```

but I reproduced the bug you reported. The difference between `{one, two, three}` and `merged` is that `merged` is a ListArray, rather than a ListOffsetArray, and it's likely that has never been tested.

It's somewhere in here:

https://github.com/scikit-hep/awkward-1.0/blob/40fdf1e6bf427dab7923934d6180e1621ea59e73/src/awkward1/behaviors/string.py#L100-L125

Note to self: also test it in Numba.

**Comment by drahnreb** [comment] 2020-10-31 00:58
Ok, thanks for the quick reply.
I recently updated from pre-0.2.32 and experienced that bug with an array constructed via `from_arrow()` (same code and data that worked before).

The last working version was 0.2.36. Which is why I debugged 0.2.37 and tried to reproduce the bug with `mergemany()` directly (the main change in v0.2.37, and function that is called by `from_arrow`).

Interestingly, `merged` is a `NumpyArray` of `format='c'`. Not sure if [that](https://github.com/scikit-hep/awkward-1.0/blob/40fdf1e6bf427dab7923934d6180e1621ea59e73/src/libawkward/array/NumpyArray.cpp#L1593) string type is correct?

**Comment by jpivarski** [comment] 2020-10-31 01:47
There are two format strings that correspond to raw bytes, and `"c"` is one of them. Within the C++ part of Awkward, I ignore the difference between them, but I think `"c"` is more appropriate for character data.

This format is probably the reason why NumPy raised the error it did, instead of a different one, but I think there's something structural going on...

You know, maybe not... I'm slow on the uptake sometimes—maybe this is exactly it. It will be the first thing I try, anyway. Thanks for the tip!

**Closed as completed** 2020-11-02 19:00 UTC
Labels: bug
