### ISSUE TITLE
Support for physical units through pint

### ISSUE THREAD

**Issue by gipert** [scikit-hep/awkward#2788] opened 2023-10-31 13:42 UTC
### Description of new feature

[pint](https://pint.readthedocs.io) is a nice Python units library with [built-in support for NumPy arrays](https://pint.readthedocs.io/en/stable/user/numpy.html) and [other integrations](https://pint.readthedocs.io/en/stable/ecosystem.html?#pint-integrations). Would be nice to be able to propagate units with Awkward arrays too. Is there any interest/plan to have this in the future?

**Comment by agoose77** [comment] 2023-10-31 13:43
Duplicate of #2468! :)

**Closed as completed by agoose77** 2023-10-31 13:43 UTC
Labels: feature

**Comment by gipert** [comment] 2023-10-31 13:46
Ok! I thought about opening a new one, since there was not mention to Pint in #2468.

**Comment by jpivarski** [comment] 2023-10-31 14:25
That was probably in private conversations, then: we're thinking of using a Pint UnitRegistry as a source of truth about units and their relationships, but some of the handling would have to be manual. (For example, we have to implement reducers ourselves. If an array has units, `ak.sum` would preserve those units but `ak.prod` shouldn't even be possible. `ak.any` and `ak.all` would drop the units when converting numbers into booleans...)

Thus, we're recognizing Pint as the standard way to express units, to the exclusion of any other libraries that might do the same thing, and we'll try to reuse code in Pint as much as possible (e.g. in unit conflicts, which of the two should be converted to the other, and what do we multiply by to get that conversion?), but there will be limits and some things will need to be computed by hand in Awkward.

**Comment by gipert** [comment] 2023-10-31 14:45
Sounds great! Thanks a lot for elaborating. Looking forward to it!
