### ISSUE TITLE
setup.py problem;   python setup.py bdist_rpm not working 

### ISSUE THREAD

**Issue by cozzyd** [scikit-hep/awkward#562] opened 2020-11-29 05:34 UTC
Trying to do `python setup.py bdist_rpm` (since I prefer to let rpm manage the packages on my system) fails, at least on Fedora 32 with Python 3.8. 

This creates a pretty straightforward RPM .spec file that seems like it should work:
```
%prep                           
%setup -n %{name}-%{unmangled_version} -n %{name}-%{unmangled_version}
                                                                                          
%build                                                                                    
env CFLAGS="$RPM_OPT_FLAGS" python3 setup.py build

%install 
python3 setup.py install --single-version-externally-managed -O1 --root=$RPM_BUILD_ROOT --record=INSTALLED_FILES                                                                     
                                                                                          
%clean       
rm -rf $RPM_BUILD_ROOT    
                                                                                          
%files -f INSTALLED_FILES             
%defattr(-,root,root)     
```

There are no apparent compilation issues, and the install step works (I verified by adding an extra printout at the end of run() in the Install class in setup.py), but then I get this error.

`error: File not found: /home/cozzyd/Downloads/awkward-1.0/build/bdist.linux-x86_64/rpm/BUILDROOT/awkward1-0.4.5-1.x86_64/usr/lib64/python3.8/site-packages/awkward.cpython-38-x86_64-linux-gnu.so`

While this file does not exist, it is listed in INSTALLED_FILES, which means somehow setuptools misrecorded the list of files for some reason (I attached the INSTALLED_FILES, with a .txt extension to make GitHub happy) 

[INSTALLED_FILES.txt](https://github.com/scikit-hep/awkward-1.0/files/5611654/INSTALLED_FILES.txt)

This is very similar to the problem reported in #182, where a `pip install -e .` failed on a completely different platform with a similar error, although that had nothing to do with trying to build an rpm, suggesting there is something a little funny about the setup.py. Note that none of the real .so files in  site-packages/awkward1 made it into INSTALLED_FILES either

My guess is somehow the install step is supposed to tell setuptools what files it needs to install, but I'm completely ignorant of setuptools internals, so it's not obvious what the problem is. 

It seems like the name it picks is derived from:
```
ext_modules = [
    CMakeExtension("awkward"),
]
```
If I change `"awkward"` to "awkward1/_ext" then it looks for (one of?) the correct file, but it copies the .so's to the wrong place (now to awkward1/awkward1), so obviously that's not right either, but suggests a place to look. Probably the answer is obvious to someone who knows more than nothing about setuptools internals :).

**Comment by jpivarski** [comment] 2020-12-01 19:07
I couldn't reproduce this on my APT-based system, and I don't have any familiarity with RPM-based systems.

Things might be different now that the Python package name is "awkward", rather than "awkward1" (as of [1.0.0rc1](https://github.com/scikit-hep/awkward-1.0/releases/tag/1.0.0rc1)).

The CMakeExtension is our own class, a subclass of `setuptools.Extension`, and the name given here is used to help it find its way around the directories—which are different on Windows vs everything else. If `bdist_rpm` needs this name to be one thing and we need the name to be another thing for directory navigation, it would be possible to modify setup.py to do so. But someone with a lot more knowledge about RPMs would have to describe the constraints.

**Comment by cozzyd** [comment] 2020-12-02 16:29
Hi Jim,

I'm thinking that this has nothing to do with RPM in particular, but
that python setup.py install --record lists the wrong files for some
reason. You can test this by e.g.

mkdir testprefix
python setup.py install --prefix=`pwd`/testprefix --record=recorded_files.txt

and then inspecting recorded_files.txt, which doesn't list all of them,
despite the fact that the correct files are actually installed to the
prefix. It looks like there's only a custom handler for copying include
files, which are not the issue.  I checked that this happens now too
after the package was renamed.

This could be a bug in setuptools, although the argument passed to
CMakeExtension seems to affect what is recorded, so I think it probably
needs slightly more information somehow. A very cursory look into
setuptools/disttools suggests that each "step" needs to report its
outputs somehow, but I have to look more into it to figure out what's
going on. 


Thanks,
-Cosmin

**Comment by jpivarski** [comment] 2020-12-02 16:32
I didn't know about the `--record` argument, but I can try to make that log correctly list all the files that would be included in the package.

**Comment by cozzyd** [comment] 2020-12-02 16:34
Yeah, it's what various pieces (including RPM building and I assume
uninstalling) rely on.

**Comment by jpivarski** [comment] 2020-12-07 20:29
PR #562 fixes the `setup.py --record` argument so that its list of files matches the files that are actually installed. This involved adding includes, shared and static libraries, and correcting the name of the extension module. As far as I can tell, only RPM distribution uses this `--record` parameter (comments in setuptools explicitly reference the RPM case, which is suggestive, and there's very little documentation on it).

PR #562 will close this issue, but that doesn't necessarily mean that `bdist_rpm` will work, only that `--record` will be correct. Depending on the nature of the remaining issues (if any), I might not be able to help because I don't actually know about/can't run RPM-building.

**Closed as completed** 2020-12-07 22:15 UTC
Labels: bug (unverified), installation

**Comment by cozzyd** [comment] 2020-12-07 23:46
Hi Jim,

Thanks, this helps a lot!

I can now generate a usable rpm, with the small caveat that out of the
box, debuginfo generation doesn't work. This is probably not a big deal
to most people, other than that it might lead to a build error with
some versions of rpm (that can be worked around easily).  

The problem of course arises because the default build type is Release.
If I just change the CMake build type to RelWithDebInfo (by modifying
setup.py), building debuginfo works fine as expected. Debug would
probably also work, and I think has a command-line flag, but I imagine
that would be slower. 

In case anybody other than me is interested, here are some basic
instructions:

#If you don't care about debuginfo, and you are using a recent enough 
# version of rpm that it complains about no debuginfo, this is the 
# simplest workaroud. You can reenable afterwards if you care.
# Necessary on Fedora 33, probably not on Fedora 32 or EL 7/8. 

   echo '%debug_package %{nil}' >> ~/.rpmmacros

# Otherwise, you can just change Release to RelWithDebInfo on line 62 of setup.py

# Then, build the RPM:
   python setup.py bdist_rpm --requires='python3-numpy >= 1.13' 

# and install it. This glob also installs debuginfo if you enabled it
   sudo dnf localinstall dist/awkward*.`arch`.rpm  # or yum if EL 7/8


Thanks,
-Cosmin

**Comment by jpivarski** [comment] 2020-12-08 00:07
The CMake type shouldn't be Debug, but I don't know the consequences of Release versus RelWithDebInfo.

According to https://stackoverflow.com/a/48755129/1623645, RelWithDebInfo sounds like a good idea. Even if we're not making RPMs, having human-readable debugging symbols around is likely to be useful. It doesn't slow down the runtime execution.

I'm willing to accept the changes you've described above as a pull request (adding the `.rpmmacros` file, for instance).

**Comment by cozzyd** [comment] 2020-12-08 01:12
Hi Jim,

The ~/.rpmmacros is per-user (NOT .rpmmacros), so it does not make
sense to package that (silly, I know...). At least I don't think RPM
supports reading from the cwd to do that.

Defaulting or adding the option to build RelWithDebInfo would be a
better solution I think. This (to my understanding) is the equivalent
of just adding -g to the Release build, so that the debugging symbols
get generated (although, since it's optimized, sometimes the debug
symbols are confusing because the compiler has rearranged or inlined
some things). Checking the compiler command line with make VERBOSE=1
confirms that that's true in this case at least (in particular, 
-DNDEBUG is present in both Release and RelWithDebInfo, so things like
asserts etc. are the same)

RelWithDebInfo's only disadvantage (if you're not trying to hide debug
symbols like proprietary vendors do) is that the generated files are
bigger, but it makes debugging/bug reports/profiling a lot easier.  
Some packaging systems (.deb and .rpm) support separating the debuginfo
into a separate package for size reasons, but I don't know if pip or
conda can do that. Hopefully they at least compress the binary files
for distribution. 

Doing the cmake build in Release vs. RelWithDebInfo options (gcc
10.2.1):

Release:

ls -alh libawkward*
-rwxrwxr-x. 1 cozzy cozzy 643K Dec  7 18:53 libawkward-cpu-kernels.so
-rw-rw-r--. 1 cozzy cozzy 1.4M Dec  7 18:53 libawkward-cpu-kernels-
static.a
-rwxrwxr-x. 1 cozzy cozzy 5.4M Dec  7 18:53 libawkward.so
-rw-rw-r--. 1 cozzy cozzy  11M Dec  7 18:53 libawkward-static.a

RelWithDebInfo:

ls -alh libawkward*
-rwxrwxr-x. 1 cozzy cozzy 8.9M Dec  7 18:51 libawkward-cpu-kernels.so
-rw-rw-r--. 1 cozzy cozzy  22M Dec  7 18:51 libawkward-cpu-kernels-
static.a
-rwxrwxr-x. 1 cozzy cozzy  97M Dec  7 18:51 libawkward.so
-rw-rw-r--. 1 cozzy cozzy 229M Dec  7 18:51 libawkward-static.a


Compressed sizes are obviously smaller (the debuginfo RPM generated on
my system is 43 M, not sure what compression RPM uses nowadays), but
it's possible that the installed size is too large to make DebugInfo
the default if the debuginfo can't be easily split from the rest of the
with pip/conda? Especially for users who might be using this on a
cluster with a small disk quota. That said, I imagine the static
libraries don't have a huge number of users?

Thanks,
-Cosmin

On Mon, 2020-12-07 at 16:07 -0800, Jim Pivarski wrote:
The CMake type shouldn't be Debug, but I don't know the consequences of
Release versus RelWithDebInfo.
According to https://stackoverflow.com/a/48755129/1623645,
RelWithDebInfo sounds like a good idea. Even if we're not making RPMs,
having human-readable debugging symbols around is likely to be useful.
It doesn't slow down the runtime execution.
I'm willing to accept the changes you've described above as a pull
request (adding the .rpmmacros file, for instance).

**Comment by jpivarski** [comment] 2020-12-08 16:19
I was going to say that compiled binary size doesn't matter, but checked myself because that's a matter of degree. 11 MB → 229 MB is actually too much because PyPI has a quota that I've already run into with the smaller releases. Part of the problem is that I have so many wheels. We've been talking about splitting the compiled C++ and Python parts into separate packages because the C++ part only needs one copy per platform, not one copy per platform + Python version, but that still doesn't save a lot of space.

The main thing I'm planning to do for the PyPI-space problem is to upload non-release candidates infrequently (fortnightly or monthly?) and _delete_ release candidates. That is, introduce a hierarchy in which users are only allowed to pin to these somewhat-more-major monthly releases, but can test bug-fixes on the temporary release candidates. Since there could be ~10 release candidates in each cycle, that practice would save a factor of ~10 of PyPI space.

But this RelWithDebInfo would add a factor of 20. I can't afford that.

**Comment by cozzyd** [comment] 2020-12-08 18:30
Hi Jim,

Yeah, I see the factor of 20 in the wheel size with RelWithDebInfo
(107MB vs 5.7 MB). It's only a factor of ~12 with RPM but that's
probably because RPM uses xz compression nowadays which might be
smarter about compressing the debuginfo. 

One thing that might help a little bit might be to remove the static
libraries from the distribution (just removing them from the
CMakeLists.txt INSTALL lines is fine, I think), since I suspect they're
not really used by anyone (Python should use the dynamic library, and I
suspect most if not all t C++ users also will use the dynamic
libraries). 

Without the static library, wheel sizes are:
RelWithDebInfo: 71 MB  
Release: 3.9 MB

Which is still more than a factor of 10. So probably best is to just to
make it slightly easier to enable/disable debug info. Since I don't
know much about setuptools, a hacky solution might be something like
this in setup.py: 

   cfg = os.environ['CMAKE_BUILD_TYPE'] if 'CMAKE_BUILD_TYPE' in os.environ else "Debug" if self.debug else "Release"   

which would let users do something like: 

  CMAKE_BUILD_TYPE=RelWithDebInfo python setup.py CMD

With some more sophistication, it might make sense for debuginfo to be
the default for source builds but not for binary wheels?


Thanks,
-Cosmin

**Comment by jpivarski** [comment] 2020-12-08 20:06
Well, the libraries are deliberately included in the Python packages so that people can compile against exactly the version of Awkward Array that is used by Python. It's not a _common_ use, but it is a design requirement and we have some specific use-cases lined up. This seemed to be the most robust way to do the version bookkeeping, which becomes a nightmare if they come from different sources.

Why do we need both static and dynamic libraries? Some systems, such as Windows, can't seem to mix them. But that's just a factor of 2.
