### ISSUE TITLE
Installing (and then importing) awkward1 on Windows

### ISSUE THREAD

**Issue by zoyt** [scikit-hep/awkward#430] opened 2020-09-02 20:14 UTC
Hello,

I just found this library (looks awesome, looking forward to using it), but I am getting an error on import. Installing with pip raised no problems that I recall.

I ran `import awkward1 as ak` in jupyter, and get the error:

![image](https://user-images.githubusercontent.com/64329370/92030465-ecbe0f00-ed1b-11ea-861b-6428b86601c5.png)

What causes this error, and how might I solve it? 

Thank you!

**Comment by jpivarski** [comment] 2020-09-02 20:39
Something went wrong in the installation procedure: the `awkward1._ext` (Python extension module providing compiled Awkward routines) was not compiled or not moved into its final installation position.

From the error message ("DLL load failed"), it looks like you're using Windows. If you're using pip to install and you have one of these combinations,

   * 32-bit Windows, Python 2.7
   * 64-bit Windows, Python 2.7
   * 32-bit Windows, Python 3.5
   * 64-bit Windows, Python 3.5
   * 32-bit Windows, Python 3.6
   * 64-bit Windows, Python 3.6
   * 32-bit Windows, Python 3.7
   * 64-bit Windows, Python 3.7
   * 32-bit Windows, Python 3.8
   * 64-bit Windows, Python 3.8

(see [wheels in PyPI](https://pypi.org/project/awkward1/0.2.35/#files)), then it should be installing a precompiled library. If not, pip would try to compile the library using CMake and Visual Studio, which is unlikely to work unless you have a development environment all set up. (Or perhaps I should say, "all set up the way that Azure has it," since the Azure system we use to build and deploy these wheels is the only Windows system on which I know that it works!)

Do you see what might have gone wrong in installation? Sometimes it's necessary to pass `--no-cache-dir` to pip if installation failed the first time but you've fixed your procedure and don't want it to draw from the broken installation.

(The fact that you're using Jupyter _might_ be relevant, since Jupyter can sometimes run with a different search path to Python libraries than Python on the commandline. To diagnose this error, you might want to try both.)

**Comment by zoyt** [comment] 2020-09-03 20:10
Interesting. I am running Python 3.8.3 on 64-bit Windows, installing other libraries recently has been fine.

I will readily admit that I need to do more reading up on how wheels and other structures in python actually work, and how they are build so that I can have more useful conversation when I encounter issues. 

I can't tell in your post whether you are asking me to further look into the installation process, or whether that was a rhetorical and there was something else for me to pick up which I missed. Would you mind reiterating?

Very possible I misinterpreted you, but I also tried passing `--no-cache-dir` to pip and retrying: `pip install awkward1 --no-cache-dir`. This returned (1). 

If it is helpful, `help("modules")` from command line finds awkward1 pictured in (2), but `import awkward1` from the commandline raises the error pictured in (3).

(1)
![image](https://user-images.githubusercontent.com/64329370/92162074-691d2480-ede6-11ea-8945-b3d88886ac65.png)
(2)
![image](https://user-images.githubusercontent.com/64329370/92160971-b6989200-ede4-11ea-88dc-5922c72958d2.png)
(3)
![image](https://user-images.githubusercontent.com/64329370/92161385-6e2da400-ede5-11ea-9142-ea48c7eaf181.png)

Thoughts?

**Comment by jpivarski** [comment] 2020-09-03 21:37
> I can't tell in your post whether you are asking me to further look into the installation process, or whether that was a rhetorical and there was something else for me to pick up which I missed. Would you mind reiterating?

I can't diagnose an installation error—it has something to do with particular files in particular places on your computer, which I don't have access to.

Python installation procedures have too much freedom:

![](https://imgs.xkcd.com/comics/python_environment.png)

so it often helps to pick only one way of installing things and stick to it. Personally, I use Miniconda—packages that can only be installed with pip (like awkward1) are installed in the same environment as long as Miniconda is in the path.

When I've presented tutorials, it was always the case that some 10% of the users couldn't install the software because of variance in laptop configurations. For the Windows users, the typical difficulty was getting to a terminal that has Miniconda/Anaconda in the path: Anaconda has its own terminal-like thing that has to be used instead of a normal terminal. It was hard following all the variations in laptop configurations when I could look over peoples' shoulders to see what was happening. Debugging it remotely is a non-starter.

So my comment above was a list of things you can try to debug it, since you're the only one in a position to do that.

Another suggestion: try

```bash
pip uninstall awkward1
```

enough times to be sure there are no versions of it on the computer. If you have a full disk search, try searching for files with "awkward1" in their names to be sure it's gone. Then start from the beginning.

If you have `awkward1_cuda_kernels` on your computer, remove it. It only works in Linux (and the wheel is labeled "Linux", so pip shouldn't have allowed it to be downloaded to your computer).

As a last-minute thought, it occurred to me that I should verify that the wheels I'm publishing have the `awkward1._ext` module in them. You're using Python 3.8 on 64-bit Windows, so that's [awkward1-0.2.35-cp38-cp38-win_amd64.whl](https://files.pythonhosted.org/packages/a8/a3/692dacf01b1af73777e58dde35569d7245e2e0f9a8e81b54048d05fd8272/awkward1-0.2.35-cp38-cp38-win_amd64.whl). I downloaded it and unzipped it (Python wheels are just ZIP files) and indeed it contains

```
awkward1/_ext.cp38-win_amd64.pyd
```

which is the DLL that your Python needs to be finding.

One last-last thought: you're running standard Python, not PyPy or anything, right? The DLL is labeled for CPython (standard Python), which alternatives like PyPy can't run. (Alternative Python implementations can't run extension modules in general.)

**Comment by Superharz** [comment] 2020-09-19 13:16
Hello,

I just tried to run uproot4 for the first time and I think to have run into the same error:

![grafik](https://user-images.githubusercontent.com/11306732/93667906-9bd34800-fa89-11ea-8ead-ab4f8c7e7881.png)
![grafik](https://user-images.githubusercontent.com/11306732/93667952-be656100-fa89-11ea-8482-7978354c49be.png)
![grafik](https://user-images.githubusercontent.com/11306732/93668041-506d6980-fa8a-11ea-8a71-ea7f5434ddb1.png)

The first image is uproot4 (v. 0.0.27) and awkward1 (v. 0.2.38) being installed by pip. The second image is the same being installed by conda from the conda-forge rep. The last image is the setup from the second image but executed directly from the command line.

I'm using numpy 1.19.1 and python 3.8.5 both from conda-forge.

**Comment by jpivarski** [comment] 2020-09-19 13:57
You're using Python 3.8 and (I assume) Windows 64-bit, so I just manually downloaded the appropriate wheel from pip:

https://files.pythonhosted.org/packages/21/15/8b710df9cdd88be9fbace2a1b85c6453da60d6574d352a295353c2614c12/awkward1-0.2.38-cp38-cp38-win_amd64.whl

and checked inside: it has a `_ext.cp38-win_amd64.pyd` file.

Could you list `C:\ProgramData\Anaconda3_8\envs\work\lib\site-packages\awkward1\_ext.*`? I think you should find

   * `_ext.cp38-win_amd64.pyd`
   * `_ext.lib`
   * `_ext.exp`

To be honest, I don't understand dynamically loadable libraries on Windows well enough to know if or why three files are needed, rather than the single `_ext.cpython-38-x86_64-linux-gnu.so` that is used by Linux (or `.dylib` on MacOS).

Actually, I don't have any positive confirmation that anyone has been able to install awkward1 on Windows. The wheels contain all the right files, but that doesn't mean it will work. @gordonwatts and @kpedro88, have you ever tried `pip install awkward1` on Windows?

As of the last few days, awkward1 and uproot4 are available on conda-forge:

   * https://anaconda.org/conda-forge/awkward1
   * https://anaconda.org/conda-forge/uproot4

This is another avenue to try, though you should `pip uninstall awkward1 uproot4` before attempting it. (Cleaning previous installation attempts is good practice in general.)

**Comment by Superharz** [comment] 2020-09-19 14:36
Yes. I'm using Windows 10 v. 1909 64-bit.

The files in `C:\ProgramData\Anaconda3_8\envs\work\lib\site-packages\awkward1\_ext.*` are identically to the three you named:

![grafik](https://user-images.githubusercontent.com/11306732/93669669-0ee2bb80-fa96-11ea-82f2-a22405a43611.png)

I already tried the conda-forge version and the error stays the same (it's the second and third picture from my first comment).

**Comment by jpivarski** [comment] 2020-09-19 14:51
Thanks for checking. I pinged @gordonwatts and @kpedro88 because they are two Windows power-users that I personally know, but now I also posted a more general call for Windows testers on https://gitter.im/HSF/PyHEP .

Without knowing of any successful installations, I don't know if the Windows wheels are broken for all Windows users or if there's something particular about your two computers. (I started with that assumption when addressing @zoyt's problem, but hadn't considered that maybe it's more general.)

**Comment by Superharz** [comment] 2020-09-19 15:31
I tried to build awkward1 locally. I don't know if I did it correctly as I'm not used to building Python Packages from source.
Anyway, it results in the attached error:

[myoutput.txt](https://github.com/scikit-hep/awkward-1.0/files/5250105/myoutput.txt)

**Comment by Superharz** [comment] 2020-09-20 01:40
The error stays the same on a Python 3.7 enviroment.

**Comment by jpivarski** [comment] 2020-09-20 03:48
I've been asking around about this. Other Windows users have hit other errors (couldn't compile with Cygwin, but we don't want it to compile at all, we want it to pick up the precompiled wheels) and still others have had no problems installing at all. I've been wondering if the Windows version matters (which version do you have?), but instructions on Python packaging for Windows only describe dependencies on Python version and 32 vs 64-bit.

I'm still searching, but we'll likely have more luck during the work week.

Both of your problems (@superharz and @voyt) have the strange combination of the library file existing, but it doesn't import ("could not be found"?!?).

**Comment by jpivarski** [comment] 2020-09-20 03:51
In case it suggests anything, the libraries you have but can't import were compiled with "Visual Studio 15 2017".

**Comment by Superharz** [comment] 2020-09-20 15:00
I noticed the following:

* Renaming `_ext.cp38-win_amd64.pyd` to something else results in `ModuleNotFoundError: No module named 'awkward1._ext'`
* Changing the import order in `layout.py` makes no difference. The error occurs by whatever is imported first from `_ext`

I tried the following:

* Installed the latest updates for W10 1909 -> No difference
* Added `Anaconda3\Library\bin` to my system environment as proposed by user1024 in [stackoverflow](https://stackoverflow.com/a/57441828) -> No difference
* Rebooted my PC -> No difference

**Comment by chrisburr** [comment] 2020-09-21 11:14
([copying over from gittter](https://gitter.im/HSF/PyHEP?at=5f6841a7d993b837e078addc))

It looks like the wheels are linking to the debug runtime instead of the release one:

![image](https://user-images.githubusercontent.com/5220533/93760294-001e1500-fc0c-11ea-88ab-834cf0911703.png)

Downloading these DLLs fixes the problem and if I check the build logs I see they contain `-- Install configuration: "Debug"` so this probably just needs to be modified to be a release build.

**Comment by jpivarski** [comment] 2020-09-21 13:46
On Gitter, I was suspicious that it's a "compiling in Debug vs Runtime" issue, but this suggests that it is:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/06b66cae-d010-441d-bc72-64a8c7cd65bc/missing-vcruntime140ddll-and-ucrtbaseddll?forum=visualstudiogeneral

I'll look into that.

**Comment by gordonwatts** [comment] 2020-09-21 13:53
Just realizing I was tagged on this - sounds like from @chrisburr a possible root cause has been found. Let me know if you want me to do test anything, @jpivarski - in general, I've not moved any of the code I used over to awkward1.

In response to an earlier question about file types:

- .dll - contains the actual code that is run.
- .lib - Exactly what is in here depends on your build process. It could be a static copy of all the awkward1 routines, for example. Or it could be stubs that call into the DLL. Regardless, they would only be used if someone was linking against the awkward libraries.
- .exp - Lists of symbols that the DLL exports. Again, used by build tools when you want to load and use the .so file.

I do not know if you intend the python distribution to have, as a use case, others linking directly against it. If that is the case... And I'm pretty sure the python shared library loader does not use the exp file. I would guess this would work fine if you got rid of the .exp file. Getting rid of the .lib file might be possible too - but I can't a-priori tell the role it plays here.

**Comment by jpivarski** [comment] 2020-09-21 17:42
@gordonwatts Thanks for the explanation!

In Linux and MacOS, we include both static and dynamic link libraries with the intention of letting [C++ projects link against the pure C++ parts](https://github.com/scikit-hep/awkward-1.0/tree/master/dependent-project), so this is a good reason to keep the .lib and .exp for awkward.dll and awkward-cpu-kernels.dll, but perhaps not _ext.dll (the Python interface to the C++ layer). We could perhaps drop _ext.lib and _ext.exp, but maybe not just yet.

**Comment by jpivarski** [comment] 2020-09-21 17:52
@Superharz and @zoyt, I managed to get the build process to say

```
2020-09-21T17:34:55.6723805Z     -- Install configuration: "Release"
```

instead of "Debug", so maybe it will look for non-debug versions of `MSVCP140D.dll`, `VCRUNTIME140D.dll`, and `ucrtbased.dll`. The files are in

https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=4279&view=artifacts&type=publishedArtifacts

(NOT on PyPI; this is a testing area before deploying.) Could you uninstall any copies of awkward1 you have (`pip uninstall awkward1` and `conda remove awkward1` if you used conda at any point, possibly multiple times for pip if several versions were involved), download the appropriate wheel for your Python version and 32-bit vs 64-bit, and install that wheel with

```bash
pip install path\to\wheel\file.whl
```

([installing from a wheel file](https://stackoverflow.com/a/27909082/1623645)).

@Superharz, since you installed the debug libraries, could you try it without them? Thanks!

**Comment by Superharz** [comment] 2020-09-21 18:14
I downloaded the wheel from Azure:

The `.dll` files look good:

![grafik](https://user-images.githubusercontent.com/11306732/93804572-cd454280-fc46-11ea-8a61-ce6b44d7ae76.png)

The import throws no error:

![grafik](https://user-images.githubusercontent.com/11306732/93804616-dfbf7c00-fc46-11ea-8461-1427d366fe06.png)

**Comment by jpivarski** [comment] 2020-09-21 18:22
That's a very good sign! Here's a minimal but non-trivial test to be sure that we're using the C++ part:

```python
>>> array = ak.Array([[1, 2, 3], [], [4, 5]])
>>> array
<Array [[1, 2, 3], [], [4, 5]] type='3 * var * int64'>
>>> ak.sum(array, axis=1)
<Array [6, 0, 9] type='3 * int64'>
```

Does that work? If so, then I'll deploy this release and it will be available as a regular thing.

**Comment by Superharz** [comment] 2020-09-21 18:32
It seems to work:

![grafik](https://user-images.githubusercontent.com/11306732/93806491-8147cd00-fc49-11ea-894b-4c86166308c5.png)

**Comment by jpivarski** [comment] 2020-09-21 18:38
Then I think it's in good shape. I'll keep this issue open until the new release is deployed (0.3.0), which should be within an hour or so.

Thanks for bearing with us while we struggled to figure this out.

(And thanks @chrisburr: you figured out the key piece, the fact that the library was being released in debug mode. I think it compiled both debug and release, because the final fix didn't change the build step, it was to explicitly pass the `--config Release` to the installation step.)

**Comment by jpivarski** [comment] 2020-09-21 20:55
The Windows wheels for this release are out. I had trouble with the PyPI limit and had to remove old releases (and [ask for an increase](https://github.com/pypa/pypi-support/issues/630)), so the release still isn't finished—it will be another half hour at least.

It should be possible to do a regular `pip install` now, though you don't strictly need to because the official wheel is no different from the one you already have.

**Closed as completed by jpivarski** 2020-09-21 20:55 UTC
Labels: installation
