### ISSUE TITLE
Default __array_function__ behavior

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/awkward#630] opened 2021-01-02 00:55 UTC
I wonder if it is reasonable to attempt calling `ak.to_numpy` on each awkward array passed to a NEP18 `__array_function__` that doesn't have an explicit override already, and if the awkward array is not expressible in numpy then display a suitably descriptive error like "no implementation found and the argument <Array ...> was not coercible to a numpy array"

This would avoid errors such as:
```
TypeError: no implementation found for 'numpy.histogram' on types that implement __array_function__: [<class 'awkward.highlevel.Array'>, <class 'numpy.ndarray'>]
```
when in reality the awkward array may well be compatible with the NEP18 function.

**Comment by jpivarski** [comment] 2021-01-02 03:04
This is a semi-duplicate of #595, where I was thinking that we'd enumerate them all in a submodule.

However, your idea of doing it outside of the decorator as a default is a different (and probably better) idea. Here's the thing, though: it should automatically call `__array__` on all the arguments that are supposed to be arrays and not on the ones that aren't. Maybe I can inspect the NumPy docstrings?!?

**Closed as completed** 2021-07-15 19:58 UTC
Labels: duplicate, feature
