### ISSUE TITLE
Unintuitive results working with nullable data (from parquet)

### ISSUE THREAD

**Issue by raymondEhlers** [scikit-hep/awkward#393] opened 2020-08-16 23:53 UTC
I've opened some trees with uproot4 and written the arrays in the parquet format using `ak.to_parquet` (from some quick tests that I ran, reading from parquet files seems much faster for doubly jagged arrays as compared to TTrees). When the parquet file is read back, from the docs I understand that the type is not exactly the same because the fields are nullable. This appears to lead to some unintuitive results (for the same data, `arrays` is loaded from the parquet file, while`arrays_original` is read directly via uproot):

```python
In [1]: arrays_original["data.fJetPt"].layout
Out[1]: <NumpyArray format="f" shape="25109" data="22.3846 21.4953 20.3251 26.6239 23.0994 ... 21.6158 21.8578 22.133 26.5842 20.8287" at="0x7fafb6180000"/>

In [2]: arrays_original["data.fJetPt"] > 0
Out[2]: <Array [True, True, True, ... True, True, True] type='25109 * bool'>

In [3]: arrays["data.fJetPt"].layout
Out[3]:
<BitMaskedArray valid_when="true" length="25109" lsb_order="true">
    <mask><IndexU8 i="[255 255 255 255 255 ... 255 255 255 255 31]" offset="0" length="3139" at="0x0001114b0000"/></mask>
    <content><NumpyArray format="f" shape="25109" data="22.3846 21.4953 20.3251 26.6239 23.0994 ... 21.6158 21.8578 22.133 26.5842 20.8287" at="0x0001140be600"/></content>
</BitMaskedArray>

In [4]: arrays["data.fJetPt"] > 0
Out[4]: <Array [None, None, None, ... None, None, None] type='25109 * ?bool'>
```

The output from [4] is not so intuitive from my perspective. My expectation was that it would evaluate to a mask, and if there were somehow missing values (which isn't the case here), then either leave them as None, or return False (because the condition couldn't be evaluated). I think I can sort of follow what's happening: the array is wrapped in a `BitMaskedArray` (hence the nullable), so asking for `bool > 0` is interpreted as a comparison that can't be made, and it returns `None`. I also see that I can work with the arrays as normal by `ak.fill_none(arrays["data.fJetPt"], 0)`, which then makes the types non-nullable.

I'm filling this as a bug report because it seems confusing, but it could alternatively be interpreted as a documentation request to add a note to the arrow conversion page that users will likely want to apply `fill_none` (not ideal if you actually mean to have `None`, but I'm not sure what to do in that case). Otherwise, it seems that many of the `ak` functions don't work (for example, `ak.to_numpy` also doesn't work), which can be rather confusing.

Thanks!

**Comment by jpivarski** [comment] 2020-08-17 11:50
Yeah, I would call this a bug. The Parquet file does change the type because everything in Parquet (and Arrow) is nullable—absolutely every level of every structure. Ideally, the Parquet writer shouldn't be creating useless bitmaps, because the format is capable of saying, "all values are valid" without creating a bitmap of "on" bits (255), but that's an efficiency issue in pyarrow.

So you do get back arrays that in principle can contain None, but in practice don't. That's why `Out[4]` is wrong. If none of the `fJetPt` values were None, then none of their comparisons with 0 would be None, either. The rules of slicing and other mathematical operations with None values are defined such that Nones pass through—if you don't have any Nones in, you shouldn't have any Nones out.

I'll take a look at this. I might need to see how you write the Parquet file to reproduce it.

**Comment by jpivarski** [comment] 2020-08-17 12:21
Step 1: I've reproduced it:

```python
>>> import awkward1 as ak
>>> original = ak.Array([0, 1, 2, 3, 4])
>>> original > 1
<Array [False, False, True, True, True] type='5 * bool'>
>>> ak.to_parquet(original, "tmp.parquet")
>>> fromparquet = ak.from_parquet("tmp.parquet")
>>> fromparquet
<Array [0, 1, 2, 3, 4] type='5 * ?int64'>
>>> fromparquet > 1
<Array [None, None, None, None, None] type='5 * ?bool'>
>>> fromparquet.layout
<BitMaskedArray valid_when="true" length="5" lsb_order="true">
    <mask><IndexU8 i="[31]" offset="0" length="1" at="0x7fef1cd93080"/></mask>
    <content><NumpyArray format="l" shape="5" data="0 1 2 3 4" at="0x7fef1cd93040"/></content>
</BitMaskedArray>
```

so I won't need an example of how you wrote it to Parquet—the above works. (Also, it's entirely possible it's not the Parquet-writing that's at fault, but something about the BitMaskedArray. I'll try making one directly.

**Comment by jpivarski** [comment] 2020-08-17 12:29
Step 2: yes, it's a problem with [BitMaskedArrays](https://awkward-array.readthedocs.io/en/latest/ak.layout.BitMaskedArray.html), which are usually only created in conversions from Arrow or Parquet (most Awkward operations use [IndexedOptionArrays](https://awkward-array.readthedocs.io/en/latest/ak.layout.IndexedOptionArray.html), or [ByteMaskedArrays](https://awkward-array.readthedocs.io/en/latest/ak.layout.ByteMaskedArray.html) if a mask is appropriate at all).

```python
>>> content = ak.layout.NumpyArray(np.array([0, 1, 2, 3, 4]))
>>> np.packbits([1, 1, 1, 1, 1, 0, 0, 0], bitorder="little")
array([31], dtype=uint8)
>>> mask = ak.layout.IndexU8(np.packbits([1, 1, 1, 1, 1, 0, 0, 0], bitorder="little"))
>>> bitmasked = ak.layout.BitMaskedArray(mask, content, valid_when=True, length=5, lsb_order=True)
>>> ak.Array(bitmasked)
<Array [0, 1, 2, 3, 4] type='5 * ?int64'>
>>> ak.Array(bitmasked) > 1
<Array [None, None, None, None, None] type='5 * ?bool'>
```

But as a ByteMaskedArray,

```python
>>> bitmasked.toByteMaskedArray()    # get exactly the same thing as a ByteMaskedArray
<ByteMaskedArray valid_when="true">
    <mask><Index8 i="[1 1 1 1 1]" offset="0" length="5" at="0x5631bbcf3c40"/></mask>
    <content><NumpyArray format="l" shape="5" data="0 1 2 3 4" at="0x5631bbd00a40"/></content>
</ByteMaskedArray>
>>> ak.Array(bitmasked.toByteMaskedArray())
<Array [0, 1, 2, 3, 4] type='5 * ?int64'>
>>> ak.Array(bitmasked.toByteMaskedArray()) > 1
<Array [False, False, True, True, True] type='5 * ?bool'>
```

So I'll look into what's happening with BitMaskedArrays in ufuncs (like `>`). It could be that `valid_when` is not checked or is reversed.

**Comment by raymondEhlers** [comment] 2020-08-17 12:33
Thanks Jim - your quick responses are always appreciated! By the time I saw the notification and got around to starting on a reproducer, you already managed it :-)

**Comment by jpivarski** [comment] 2020-08-17 12:35
(I find that if I don't deal with these things right away, other things intervene and I end up never getting back to them. If it's a bug, I don't want it to go unfixed.)

**Comment by jpivarski** [comment] 2020-08-17 13:13
The PR above fixes it:

```diff
index e3631dd..bd38f1b 100644
--- a/src/libawkward/array/BitMaskedArray.cpp
+++ b/src/libawkward/array/BitMaskedArray.cpp
@@ -248,7 +248,7 @@ namespace awkward {
       bytemask.data(),
       mask_.data(),
       mask_.length(),
-      false,
+      valid_when_,
       lsb_order_);
     util::handle_error(err, classname(), identities_.get());
     return bytemask.getitem_range_nowrap(0, length_);
```

When all tests pass, it will be merged into master, but the next release could be days from now (trying to include a lot of GPU developments). In the meantime, conversions of BitMaskedArray into other types of option-type arrays (ByteMaskedArray, IndexedOptionArray, UnmaskedArray) do work, and those other array types correctly handle ufuncs like `>`. One easy way to force conversion is to multiply by 1:

```python
>>> a = awkward1.layout.BitMaskedArray(awkward1.layout.IndexU8(numpy.array([31], numpy.uint8)), awkward1.layout.NumpyArray(numpy.array([0, 1, 2, 3, 4])), valid_when=True, length=5, lsb_order=True)
>>> a = awkward1.Array(awkward1.layout.BitMaskedArray(awkward1.layout.IndexU8(numpy.array([31], numpy.uint8)), awkward1.layout.NumpyArray(numpy.array([0, 1, 2, 3, 4])), valid_when=True, length=5, lsb_order=True))
>>> a
<Array [0, 1, 2, 3, 4] type='5 * ?int64'>
>>> a.layout
<BitMaskedArray valid_when="true" length="5" lsb_order="true">
    <mask><IndexU8 i="[31]" offset="0" length="1" at="0x5605b5f724b0"/></mask>
    <content><NumpyArray format="l" shape="5" data="0 1 2 3 4" at="0x5605b5f57470"/></content>
</BitMaskedArray>
>>> a * 1
<Array [0, 1, 2, 3, 4] type='5 * ?int64'>
>>> (a * 1).layout
<IndexedOptionArray64>
    <index><Index64 i="[0 1 2 3 4]" offset="0" length="5" at="0x5605b5fd7e10"/></index>
    <content><NumpyArray format="l" shape="5" data="0 1 2 3 4" at="0x5605b5f9d7d0"/></content>
</IndexedOptionArray64>
>>> (a * 1) > 1
<Array [False, False, True, True, True] type='5 * ?bool'>
```

Or you could get the latest version from master. (The tests will be done in about 15 minutes.)

**Comment by raymondEhlers** [comment] 2020-08-17 13:34
Outstanding, thank you Jim! I'll check out the master after the PR merges

**Comment by jpivarski** [comment] 2020-08-17 13:36
It's merged. Enjoy!

**Closed as completed** 2020-08-17 13:35 UTC
Labels: bug
