### ISSUE TITLE
Adding empty_like, zeros_like, ones_like?

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/awkward#529] opened 2020-11-12 12:38 UTC
I checked the docs and it seems like the functions `empty_like`, `zeros_like` and `ones_like` are currently missing from awkward1. I think it would be great to have these, they are commonly needed when writing some array transforms. Ideally, these should also be available in Numba-compiled Python.

**Comment by jpivarski** [comment] 2020-11-12 14:22
This is a duplicate of #493, which is on the project board for November. (Since it came up multiple times, I'll mentally bump it up in priority.)

Just a note: since Awkward Arrays are immutable, there would be no advantage to having an `empty_like`, but `zeros_like` and `ones_like` are well-motivated.

**Closed as completed by jpivarski** 2020-11-12 14:22 UTC
Labels: duplicate, feature

**Comment by HDembinski** [comment] 2020-11-12 18:18
I didn't know they are immutable. So I always have to build them incrementally, even if I know the total size in advance?

**Comment by HDembinski** [comment] 2020-11-12 18:19
I was assuming mutable arrays. I don't understand why the values should be immutable. I suppose it is part of the abstraction, but it seems like a very harsh requirement for a ListOffsetArray

**Comment by jpivarski** [comment] 2020-11-12 19:07
I mention this at every opportunity—I don't remember who I've told, but I've had this conversation many times.  `:)`  Awkward Arrays have been immutable since an early prototype in summer 2018 when I found that managing mutability—just from the perspective of interface—is too complex. View-vs-copy is a significant issue when using NumPy, but at least in NumPy, an array is either entirely a view or entirely a copy. Most Awkward Arrays are part-view, part-new. It quickly gets impossible to keep track of which arrays are linked by shared memory, so changes are non-local in surprising ways.

It _is_ possible to make an Awkward Array a view of a NumPy array and then mutate that NumPy array. Any mutation would require deep knowledge of an Awkward Array's `layout`, so the fact that this method requires such knowledge isn't an additional burden. Such a technique can be used in high-performance situations: see [this part of the docs](https://awkward-array.org/how-to-convert-numpy.html#mutability-of-awkward-arrays-from-numpy).

At this moment, I was just working on `ak.ones_like` and `ak.full_like`, which create arrays like `["1", "1", "1", ..., "1"]` when the original array has string type. I was building it like

```python
>>> ak.Array(ak.layout.ListArray64(
...     ak.layout.Index64(np.full(1000, 0)),
...     ak.layout.Index64(np.full(1000, 5)),
...     ak.layout.NumpyArray(np.frombuffer(b"hello", np.uint8), parameters={"__array__": "char"}),
...     parameters={"__array__": "bytestring"}))
<Array ['hello', 'hello', ... 'hello', 'hello'] type='1000 * bytes'>
```

which actually has only one `'hello'`, but repeating starts of `[0, 0, 0, ..., 0]` and stops of `[5, 5, 5, ..., 5]` made a logical array with a thousand strings in it. Some steps of processing would leave it as one internal `'hello'`, but other steps would force the `'hello'` to get duplicated. If the array you have is of the former type, then assigning one character in one of these strings would make all of these strings change. If it's the latter type, then it would only change one. This is what it means to need deep knowledge of the "layout."

For building up arrays, there's the [ak.ArrayBuilder](https://awkward-array.readthedocs.io/en/latest/_auto/ak.ArrayBuilder.html), though this isn't the fastest possible way to build a structure, even in Numba. There's a solution to the general problem, with layout-dependent hacks to speed up special cases, but there's an intermediate case that needs to be better developed: fast-building of an array when you fully know the type. That could be improved.

**Comment by HDembinski** [comment] 2020-11-17 16:11
*Note: I will use `Array` when I talk about an awkward array and `ndarray` when I talk about numpy*

Ok, thank you for the explanation. I didn't know that `.to_numpy` produces a mutable view even if the Array itself is immutable. So in theory, I could create an Array with `empty_like` (which then actually has a use!) then generate a numpy view of it and manipulate the Array with the ndarray.

I haven't tried what happens when I try to do `to_numpy` on a ListOffsetArray.

**Comment by jpivarski** [comment] 2020-11-17 17:25
The two patterns described [here](https://awkward-array.org/how-to-convert-numpy.html#mutability-of-awkward-arrays-from-numpy) and [here](https://awkward-array.org/how-to-convert-numpy.html#mutability-of-awkward-arrays-converted-to-numpy) are: (1) create an `ndarray` and wrap it as `ak.Array`, then mutate the `ndarray`, and (2) create an `ak.Array` and extract the underlying `ndarray`, which you can mutate.

Following either of those patterns necessarily gets you involved in the details of the layout, and the fact that some operations view, others copy, and most partly-view, partly-copy. So if you use these patterns, you'll need to be aware of when you transform an array with a slice or other operation because the output of that operation might have copied the data you expect to be able to mutate. You might want to do all the mutation in an early "initialization" stage and use the arrays as immutable from that point onward ("Clojure-style").

Since what you want to do depends on layout, you should extract the `ndarray` from the layout like this, not with a high-level function like `ak.to_numpy` (or equivalently, `np.asarray` applied to the high-level `ak.Array`):

```python
>>> array = probably_from_uproot()     # returning an ak.Array
>>> content = np.asarray(array.layout.content)
```

This guarantees that the `ndarray` in `content` is a view of the underlying data. If you do a high-level operation, there is no such guarantee. The symptom of the latter would be that changing the `ndarray` doesn't change the Awkward Array.
