### ISSUE TITLE
Array order dependent math failure between ListOffsetArray64 and ListOffsetArray64 containing UnionArray8_64

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#522] opened 2020-11-07 20:37 UTC
Forwarding https://github.com/CoffeaTeam/coffea/issues/367 here since it is mostly likely an issue in awkward given the trace (click link for details).

Repro is currently with NanoEvents to source data so you'll need the most recent coffea release to run this.
```python3
from coffea.nanoevents import NanoEventsFactory
fname = 'https://raw.githubusercontent.com/CoffeaTeam/coffea/master/tests/samples/nano_dy.root'
factory = NanoEventsFactory.from_file(fname)
events = factory.events()

gen_pt = awkward1.fill_none(events.Jet.matched_gen.pt, 0.)
jetPt = events.Jet.pt

print(-gen_pt + jetPt)  # produces correct answer
print(jetPt - gen_pt)  # fails with traceback as below
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/numpy/lib/mixins.py", line 21, in func
    return ufunc(self, other)
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/highlevel.py", line 1369, in __array_ufunc__
    return awkward1._connect._numpy.array_ufunc(ufunc, method, inputs, kwargs)
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_connect/_numpy.py", line 174, in array_ufunc
    inputs, getfunction, behavior, allow_records=False
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_util.py", line 996, in broadcast_and_apply
    out = apply(broadcast_pack(inputs, isscalar), 0)
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_util.py", line 759, in apply
    outcontent = apply(nextinputs, depth + 1)
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_util.py", line 847, in apply
    outcontent = apply(nextinputs, depth + 1)
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_util.py", line 589, in apply
    depth,
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_util.py", line 655, in apply
    nextinputs.append(x[mask].project(combo[str(i)]))
ValueError: no field of name 1
```

**Comment by jpivarski** [comment] 2020-11-11 20:53
Minimal reproducer:

```python
>>> content1 = ak.Array([0.0, 1.1, 2.2, 3.3, 4.4]).layout
>>> content2 = ak.Array([  0, 100, 200, 300, 400]).layout
>>> tags = ak.layout.Index8(np.array([0, 0, 0, 1, 1, 0, 0, 1, 1, 1], np.int8))
>>> index = ak.layout.Index64(np.array([0, 1, 2, 0, 1, 3, 4, 2, 3, 4], np.int64))
>>> unionarray = ak.Array(ak.layout.UnionArray8_64(tags, index, [content1, content2]))
>>> unionarray
<Array [0, 1.1, 2.2, 0, ... 4.4, 200, 300, 400] type='10 * union[float64, int64]'>
>>> unionarray + 10
<Array [10, 11.1, 12.2, 10, ... 210, 310, 410] type='10 * float64'>
>>> 10 + unionarray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/numpy/lib/mixins.py", line 31, in func
    return ufunc(other, self)
  File "/home/jpivarski/irishep/awkward-1.0/awkward1/highlevel.py", line 1369, in __array_ufunc__
    return awkward1._connect._numpy.array_ufunc(ufunc, method, inputs, kwargs)
  File "/home/jpivarski/irishep/awkward-1.0/awkward1/_connect/_numpy.py", line 173, in array_ufunc
    out = awkward1._util.broadcast_and_apply(
  File "/home/jpivarski/irishep/awkward-1.0/awkward1/_util.py", line 993, in broadcast_and_apply
    out = apply(broadcast_pack(inputs, isscalar), 0)
  File "/home/jpivarski/irishep/awkward-1.0/awkward1/_util.py", line 756, in apply
    outcontent = apply(nextinputs, depth + 1)
  File "/home/jpivarski/irishep/awkward-1.0/awkward1/_util.py", line 652, in apply
    nextinputs.append(x[mask].project(combo[str(i)]))
ValueError: no field of name 1
```

And you only get into this situation (of having a UnionArray) because of #459: floating point numbers with documentation are not being merged with floating point numbers without documentation. But anyway, I'm glad that the other bug exposed this one and will be fixing them both in one PR.

**Closed as completed** 2020-11-12 00:34 UTC
Labels: bug
