### ISSUE TITLE
awkward-cpp-14 fails to build: ImportError: cannot import name '__version__' from 'scikit_build_core._version'

### ISSUE THREAD

**Issue by yurivict** [scikit-hep/awkward#2404] opened 2023-04-15 05:00 UTC
### Version of Awkward Array

14

### Description and code to reproduce

```
===>  Building for py39-awkward-cpp-14
* Getting build dependencies for wheel...

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/scikit_build_core/__init__.py", line 10, in <module>
    from ._version import __version__
ImportError: cannot import name '__version__' from 'scikit_build_core._version' (/usr/local/lib/python3.9/site-packages/scikit_build_core/_version.py)
```

```
$ cat /usr/local/lib/python3.9/site-packages/scikit_build_core/_version.py
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.3.0'
version_tuple = (0, 3, 0)
```

What is wrong?

**Comment by jpivarski** [comment] 2023-04-15 17:39
The first thing that seems like a problem is that `pip` is trying to compile `awkward-cpp`. Either none of the many platform-Python version combinations in https://pypi.org/project/awkward-cpp/#files match your system or you intentionally asked for a recompilation with `--no-binary`. If it's the former, we'd be interested to know what system you have that is not in our list of prebuilt wheels. Maybe it could be added. If it's the latter, it would be interesting to know why you want to rebuild it from source.

But okay, assuming that it's going to be rebuilt from source, the error here is happening in Scikit-build, which is used to organize the compilation. Somehow, this Scikit-build is lacking a `__version__` string. Such a thing doesn't exist in the Scikit-build [source code](https://github.com/scikit-build/scikit-build/blob/main/skbuild/_version.pyi); presumably it's supposed to be generated when Scikit-build gets installed, which suggests that your Scikit-build is not properly installed. Any thoughts on this, @henryiii?

Although `pip` is supposed to be able to build from scratch (when an appropriate wheel can't be found or `--no-binary` is requested), there's another way to build from scratch that allows for developing, if that's what you're intending to do: https://github.com/scikit-hep/awkward#installation-for-developers

**Comment by yurivict** [comment] 2023-04-15 17:55
The OS is FreeBSD 13.1. There are no binaries.

**Comment by jpivarski** [comment] 2023-04-15 18:16
FreeBSD is an important OS with a significant share of the server market. (Last time I checked, anyway. I'm not finding figures now that substantiate this. Maybe I'm decades out of date?)

I would have thought, though, that one of the so-called "manylinux" wheels would work on FreeBSD, since "manylinux" actually just means a set of common shared libraries with minimal version numbers. Some recent FreeBSD ought to be ahead of some of the manylinux specifications. But if `pip` didn't automatically know that, I'm not sure how to check it or convince `pip` that it should have used it. Maybe the `auditwheel` tool can say something about this.

In my recent web searches, I haven't been able to find out how FreeBSD users do Python-pip installation at all.

Hmmm. https://github.com/conda/conda/issues/10450#issuecomment-812589409 Maybe you could use the "Linux compatibility layer?"

**Comment by yurivict** [comment] 2023-04-15 18:24
Yes, FreeBSD is used a lot in servers.

For ports/packages purposed we need to build a package from source.

I encountered this problem while trying to create a FreeBSD port for awkward.

**Comment by henryiii** [comment] 2023-04-15 18:34
Is it due to an old version of hatch-vcs? The current ones produce `__version__`. If you build scikit-build-core from source and have an old hatch-vcs, that might happen. I can switch this to the classic import name in the next release to be safer. 

BSD do not have the necessary forward compatibility or cross-compatibility guarantees requires to make a “manybsd” common binary platform. It’s been discussed off and on for years. But so far it’s not feasible.

**Comment by jpivarski** [comment] 2023-04-15 18:35
Okay, that makes sense. But in that case, I think the problem is with Scikit-build, awkward-cpp's build dependency. And not necessarily Scikit-build itself but the way it was installed. Is it possible to run [Scikit-build's tests](https://github.com/scikit-build/scikit-build/tree/main/tests)?

Specifically,

```
cannot import name '__version__' from 'scikit_build_core._version'
```

looks like the stopping issue here. Ah, @henryiii just responded with more insight into the problem.

**Comment by henryiii** [comment] 2023-04-16 00:42
Actually it looks like it was a change in setuptools-scm's default template, which would make it requires a recent setuptools-scm. I've switched to the previous name (which still works), so the next patch release (soonish, probably by EoD Monday) will work with those versions.

**Comment by henryiii** [comment] 2023-04-17 02:38
scikit-build-core 0.3.1 uses the old name, and came out yesterday, could you try again with that?

**Comment by agoose77** [comment] 2023-04-20 13:48
I'm going to close this issue, if that's OK with everyone involved, as it's not an issue with `awkward-cpp` :)

**Closed as completed by agoose77** 2023-04-20 13:48 UTC
Labels: installation
